### ISSUE TITLE
How-to guide for adding persistent storage buckets

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/docs#215]
Develop a "runbook" style guide for Hub Admins to configure Cloud Object Storage for their hub.

**Comment by jmunroe** [comment]
Related:
- https://github.com/2i2c-org/meta/issues/979

**Comment by choldgraf** [comment]
I hadn't thought of user docs as "runbooks" before, but I think it's cool how @jnywong framed this in the top comment. Runbooks are [ways for organizations to share knowledge from more experienced team members](https://www.pagerduty.com/resources/learn/what-is-a-runbook/). When 2i2c creates runbooks for communities to follow, we are sharing our knowledge/experience in order to empower communities to share the responsibility of running infrastructure for their service. It's also a way to share expertise and uplevel community skills.

I'm curious if this is how you're thinking about it as well...

**Comment by jnywong** [comment]
Yuvi has pointed me to check out https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/325
